### ISSUE TITLE
strftime's %B, umlauts & encode('utf8')

### ISSUE THREAD

**Issue by jayeff** [drdrang/archive-tweets#1]
The default `datefmt = '%B %-d, %Y at %-I:%M %p'` don't work with a german localized dates. The month may contains a umlaut and then the line `'\n'.join(lines).encode('utf8')` fails with a `UnicodeDecodeError`.

What happened: The string with the date is automatically decoded with the default codec (ASCII) but does not correctly decode the ä. When it later tries to encode the ascii string to utf8 the error is thrown.
You find a discussion about this here: http://bugs.python.org/issue5398 

Explicitly decoding the date like this `ts.strftime(datefmt).decode('utf8')` solves this issue for me.

Ps: Is the minus in %-d and %-I on purpose and if yes, what's the effect of it? Don't know this syntax and also seems to not work on my machine.

**Comment by drdrang** [comment]
Thanks for the bug report. I've added a decode to Line 44.

As for the minuses, they suppress leading zeros for the day and hour. Thus,

  September 5, 2012 at 6:30 PM

instead of

  September 05, 2012 at 06:30 PM

The %-\* codes are a GNU libc extension to strftime. They work in OS X and I would expect them to work in Linux, too. If your Python was compiled in an environment that doesn't have that extension, the minuses won't work. See

  http://www.leancrew.com/all-this/2012/07/dating-myself/

Regards,
Dr. Drang

**Comment by jayeff** [comment]
Strange, I'm on OS X but the %-\* codes do not work for me. I suspect that I have a different version of the libc extension. But it's fine as I prefer 0-padded numbers anyway.

Thanks for this script btw - it works great. Finally I can cross off the long-term guest 'start archiving my tweets' from the todo-list :)
